# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currencyName', models.CharField(max_length=50)),
                ('pszTimestamp', models.TextField(max_length=1024)),
                ('maxMoney', models.CharField(max_length=30)),
                ('halvingInterval', models.CharField(max_length=30)),
                ('nDefaultPort', models.CharField(max_length=65535)),
                ('nTime', models.CharField(max_length=30)),
                ('nBits', models.CharField(max_length=40)),
                ('nSubsidy', models.CharField(max_length=30)),
                ('pubKey', models.CharField(max_length=1024)),
                ('status', models.CharField(max_length=30)),
                ('githubUser', models.CharField(max_length=50)),
                ('githubPass', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('coinBase', models.CharField(max_length=30)),
                ('currencyUnit', models.CharField(max_length=3)),
                ('hashGenesisParams', models.CharField(max_length=40)),
                ('downloadPassword', models.CharField(max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DnsSeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('subDomain', models.CharField(max_length=20)),
                ('cryptoCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BonaB.CryptoCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='FullNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=45)),
                ('cryptoCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BonaB.CryptoCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='GenesisBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pszTimestamp', models.CharField(max_length=1024)),
                ('coinBase', models.CharField(max_length=50)),
                ('nBits', models.CharField(max_length=40)),
                ('nNonce', models.CharField(max_length=50)),
                ('mHash', models.CharField(max_length=200)),
                ('nTime', models.CharField(max_length=30)),
                ('pubKey', models.CharField(max_length=500)),
                ('gHash', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('cryptoCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BonaB.CryptoCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('aliasName', models.CharField(max_length=20)),
                ('haveBuild', models.BooleanField(default=False)),
                ('githubUrl', models.CharField(max_length=200)),
                ('downloadUrl', models.CharField(max_length=200)),
                ('hashCommit', models.CharField(max_length=40)),
                ('repoStatus', models.IntegerField(default=0)),
                ('buildStatus', models.IntegerField(default=0)),
                ('cryptoCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BonaB.CryptoCurrency')),
            ],
        ),
    ]
