- hosts: testserver
  become: true
  become_method: sudo
  become_user: root
  tasks:
   - name: search directory
     command: "ls {{ ansible_env.PWD }}"
     register: searchresult

   - name: creat directory
     file:
      path: "{{ ansible_env.PWD }}/json"
      state: directory
     when: "'json' not in searchresult.stdout"

   - name: directory change permission
     file:
      path: "{{ ansible_env.PWD }}/json"
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      mode: 0777
     when: "'json' not in searchresult.stdout"

   - name: search directory2
     command: "ls {{ ansible_env.PWD }}/json"
     register: searchresult2

   - name: copy files
     copy:
      src: "{{ source_json_directory }}"
      dest: "{{ ansible_env.PWD }}/json/{{ filename }}.json"
     register: jsontransfer
     when: "'{{ filename }}.json' not in searchresult2.stdout"

   - name: json change permission
     file:
      path:  "{{ ansible_env.PWD }}/json/{{ filename }}.json"
      owner: "{{ ansible_env.SUDO_USER }}"
      group: "{{ ansible_env.SUDO_USER }}"
      mode: 0777
     when: "'{{ filename }}.json' not in searchresult2.stdout"

   - name: run nvidia-docker
     command: "nvidia-docker run -v {{ ansible_env.PWD }}/json/{{ filename }}.json:/data/request.json genesisminer-docker:0.3 '--infile' /data/request.json"
     when: jsontransfer|changed

   - name: delete request.json
     file:
      path: "{{ ansible_env.PWD }}/json"
      state: absent